version = 0.1
[default.deploy.parameters]
stack_name = "ics-transformer"
resolve_s3 = true
s3_prefix = "ics-transformer"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
